EDC_APPS = (
    'edc.apps.admin_supplemental_fields',
    'edc.apps.app_configuration',
    'edc.audit',

    'edc.base.form',
    'edc.base.model',
    'edc.base.modeladmin',

    'edc.core.bhp_birt_reports',
    'edc.core.bhp_common',
    'edc.core.bhp_content_type_map',
    'edc.core.bhp_context',
    'edc.core.bhp_export_data',
    #'edc.core.bhp_nmap',
    #'edc.core.bhp_data_manager',
    'edc.core.bhp_poll_mysql',
    'edc.core.bhp_site_edc',
    'edc.core.bhp_static',
    'edc.core.bhp_string',
    'edc.core.bhp_templates',
    'edc.core.bhp_templatetags',
    'edc.core.bhp_userprofile',
    'edc.core.bhp_using',
    'edc.core.bhp_variables',
    'edc.core.crypto_fields',
    'edc.core.identifier',
    'edc.core.model_data_inspector',
    'edc.core.model_selector',

    'edc.dashboard.base',
    'edc.dashboard.search',
    'edc.dashboard.section',
    'edc.dashboard.subject',
    'edc.data_dictionary',
    'edc.data_manager',

    'edc.entry_meta_data',
    'edc.export',

    'edc.import',

    'edc.lab.lab_clinic_api',
    'edc.lab.lab_clinic_reference',
    'edc.lab.lab_packing',
    'edc.lab.lab_requisition',
    'edc.lab.lab_profile',

    'edc.map',

    'edc.notification',

    'edc.pharma.dispenser',

    'edc.subject.actg',
    'edc.subject.adverse_event',
    'edc.subject.appointment',
    'edc.subject.appointment',
    'edc.subject.appointment_helper',
    'edc.subject.code_lists',
    'edc.subject.consent',
    'edc.subject.contact',
    'edc.subject.entry',
    'edc.subject.lab_tracker',
    'edc.subject.locator',
    'edc.subject.off_study',
    'edc.subject.registration',
    'edc.subject.rule_groups',
    'edc.subject.subject',
    'edc.subject.subject_config',
    'edc.subject.subject_summary',
    'edc.subject.visit_schedule',
    'edc.subject.visit_tracking',

    'edc.testing',
    'edc.utils',
)
