from django.db import models

from ..models import InfantRando


class RandoTestHelper(models.Model):
    def populate_rando(self):

        InfantRando.objects.create(site='Gaborone', stratum='BF,HAART', sid=110140,rx='CTX',bf_duration='6months',dispensed='NO',infant_initials='XX')
        InfantRando.objects.create(site='Gaborone', stratum='BF,HAART', sid=110142,rx='CTX',bf_duration='6months',dispensed='NO',infant_initials='XX')
        InfantRando.objects.create(site='Gaborone', stratum='BF,HAART', sid=110143,rx='CTX',bf_duration='12months',dispensed='NO',infant_initials='XX')
        InfantRando.objects.create(site='Gaborone', stratum='BF,HAART', sid=110144,rx='CTX',bf_duration='12months',dispensed='NO',infant_initials='XX')
        InfantRando.objects.create(site='Gaborone', stratum='BF,HAART', sid=110172,rx='CTX',bf_duration='6months',dispensed='NO',infant_initials='XX')
        InfantRando.objects.create(site='Gaborone', stratum='BF,HAART', sid=110173,rx='CTX',bf_duration='6months',dispensed='NO',infant_initials='XX')
        InfantRando.objects.create(site='Gaborone', stratum='BF,HAART', sid=110174,rx='CTX',bf_duration='12months',dispensed='NO',infant_initials='XX')
        InfantRando.objects.create(site='Gaborone', stratum='BF,HAART', sid=110175,rx='CTX',bf_duration='12months',dispensed='NO',infant_initials='XX')
        InfantRando.objects.create(site='Gaborone', stratum='BF,notHAART', sid=110176,rx='CTX',bf_duration='6months',dispensed='NO',infant_initials='XX')
        InfantRando.objects.create(site='Gaborone', stratum='BF,notHAART', sid=110177,rx='CTX',bf_duration='6months',dispensed='NO',infant_initials='XX')
        InfantRando.objects.create(site='Gaborone', stratum='BF,notHAART', sid=110178,rx='CTX',bf_duration='12months',dispensed='NO',infant_initials='XX')
        InfantRando.objects.create(site='Gaborone', stratum='BF,notHAART', sid=110179,rx='CTX',bf_duration='12months',dispensed='NO',infant_initials='XX')
        InfantRando.objects.create(site='Gaborone', stratum='BF,notHAART', sid=110180,rx='CTX',bf_duration='6months',dispensed='NO',infant_initials='XX')
        InfantRando.objects.create(site='Gaborone', stratum='BF,notHAART', sid=110100,rx='CTX',bf_duration='6months',dispensed='NO',infant_initials='XX')
        InfantRando.objects.create(site='Gaborone', stratum='BF,notHAART', sid=110101,rx='CTX',bf_duration='12months',dispensed='NO',infant_initials='XX')
        InfantRando.objects.create(site='Gaborone', stratum='BF,notHAART', sid=110102,rx='CTX',bf_duration='12months',dispensed='NO',infant_initials='XX')
        InfantRando.objects.create(site='Gaborone', stratum='FF', sid=110145,rx='CTX',bf_duration='',dispensed='NO',infant_initials='XX')
        InfantRando.objects.create(site='Gaborone', stratum='FF', sid=110146,rx='CTX',bf_duration='',dispensed='NO',infant_initials='XX')
        InfantRando.objects.create(site='Gaborone', stratum='FF', sid=110147,rx='CTX',bf_duration='',dispensed='NO',infant_initials='XX')
        InfantRando.objects.create(site='Gaborone', stratum='BF,HAART', sid=110148,rx='Placebo',bf_duration='6months',dispensed='NO',infant_initials='XX')
        InfantRando.objects.create(site='Gaborone', stratum='BF,HAART', sid=110149,rx='Placebo',bf_duration='6months',dispensed='NO',infant_initials='XX')
        InfantRando.objects.create(site='Gaborone', stratum='BF,HAART', sid=110150,rx='Placebo',bf_duration='12months',dispensed='NO',infant_initials='XX')
        InfantRando.objects.create(site='Gaborone', stratum='BF,notHAART', sid=110151,rx='Placebo',bf_duration='12months',dispensed='NO',infant_initials='XX')
        InfantRando.objects.create(site='Gaborone', stratum='BF,notHAART', sid=110152,rx='Placebo',bf_duration='12months',dispensed='NO',infant_initials='XX')
        InfantRando.objects.create(site='Gaborone', stratum='FF', sid=110153,rx='Placebo',bf_duration='',dispensed='NO',infant_initials='XX')
        InfantRando.objects.create(site='Gaborone', stratum='FF', sid=110154,rx='Placebo',bf_duration='',dispensed='NO',infant_initials='XX')
        InfantRando.objects.create(site='Gaborone', stratum='FF', sid=110155,rx='Placebo',bf_duration='',dispensed='NO',infant_initials='XX')
        InfantRando.objects.create(site='Gaborone', stratum='FF', sid=110156,rx='Placebo',bf_duration='',dispensed='NO',infant_initials='XX')
        InfantRando.objects.create(site='Molepolole', stratum='FF', sid=110157,rx='CTX',bf_duration='',dispensed='NO',infant_initials='XX')
        InfantRando.objects.create(site='Molepolole', stratum='FF', sid=110158,rx='CTX',bf_duration='',dispensed='NO',infant_initials='XX')
        InfantRando.objects.create(site='Molepolole', stratum='FF', sid=110159,rx='CTX',bf_duration='',dispensed='NO',infant_initials='XX')
        InfantRando.objects.create(site='Molepolole', stratum='BF,HAART', sid=110160,rx='CTX',bf_duration='12months',dispensed='NO',infant_initials='XX')
        InfantRando.objects.create(site='Molepolole', stratum='BF,HAART', sid=110161,rx='CTX',bf_duration='',dispensed='NO',infant_initials='XX')
        InfantRando.objects.create(site='Molepolole', stratum='FF', sid=110162,rx='Placebo',bf_duration='',dispensed='NO',infant_initials='XX')
        InfantRando.objects.create(site='Molepolole', stratum='FF', sid=110163,rx='Placebo',bf_duration='',dispensed='NO',infant_initials='XX')
        InfantRando.objects.create(site='Molepolole', stratum='FF', sid=110164,rx='Placebo',bf_duration='',dispensed='NO',infant_initials='XX')
        InfantRando.objects.create(site='Molepolole', stratum='BF,HAART', sid=110165,rx='Placebo',bf_duration='12months',dispensed='NO',infant_initials='XX')
        InfantRando.objects.create(site='Molepolole', stratum='BF,notHAART', sid=110166,rx='Placebo',bf_duration='12months',dispensed='NO',infant_initials='XX')
        InfantRando.objects.create(site='Lobatse', stratum='FF', sid=110167,rx='CTX',bf_duration='',dispensed='NO',infant_initials='XX')
        InfantRando.objects.create(site='Lobatse', stratum='BF,HAART', sid=110168,rx='CTX',bf_duration='12months',dispensed='NO',infant_initials='XX')
        InfantRando.objects.create(site='Lobatse', stratum='FF', sid=110169,rx='Placebo',bf_duration='',dispensed='NO',infant_initials='XX')
        InfantRando.objects.create(site='Lobatse', stratum='FF', sid=110170,rx='Placebo',bf_duration='',dispensed='NO',infant_initials='XX')
        InfantRando.objects.create(site='Lobatse', stratum='BF,notHAART', sid=110171,rx='Placebo',bf_duration='12months',dispensed='NO',infant_initials='XX')
        return InfantRando.objects.all()