insert into bhp_lab_aliquottype (name,short_name, display_index) values ('Buffy coat', 'BC', 1);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('Plasma', 'PL', 2);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('DNA', 'DNA', 3);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('PBMC', 'PBMC', 4);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('SERUM', 'SERUM', 5);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('Breast Milk: Pellet', 'BMP', 6);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('Red Blood Cells', 'RBC', 7);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('Ulcer swab', 'US', 8);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('Urine', 'UR', 9);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('Semen pellet', 'SP', 10);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('Endocervical swabHIV', 'ECHIV', 11);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('Endocervical swabHSV', 'ECHSV', 12);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('Cervical Vaginal Lavage Supernatant', 'CVLS', 13);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('Cervical Vaginal Lavage SupernatantTriReagent', 'CVLST', 14);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('Plasma ACD', 'PL-ACD', 15);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('Ulcer swab HSV', 'ULHSV', 16);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('Urine Gen Probe', 'UrGen', 17);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('Endo Swab Gen Probe', 'SwGen', 18);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('serum albumin', 'alb', 19);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('Infant Nasopharyngeal Aspirate', 'NASO', 20);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('Dried Blood Spot', 'DBS', 21);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('Vaginal Swab Slide', 'VSS', 22);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('Buffy Coat DMSO', 'BC-DMSO', 23);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('Whole Blood DMSO', 'WB-DMSO', 24);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('Induced Sputum', 'INDSP', 25);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('Plasma EDTA', 'PL-EDTA', 26);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('PBMC-ACD', 'PBMC-ACD', 27);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('Whole Blood', 'WB', 28);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('Breast Milk: Whole', 'BMW', 29);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('Breast Milk: Supernatant', 'BMS', 30);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('Endocervical Swab', 'ES', 31);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('Semen supernatant', 'SS', 32);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('Aspirated Fluid', 'ASPFL', 33);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('Cervical Vaginal Lavage Cell Pellet', 'CVLCP', 34);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('Slide gram stain', 'SGS', 35);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('BV Slide Methanol Fixed', 'BVSM', 36);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('PBMC Pellet', 'PP', 37);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('bacterial cell line for research', 'bactcell', 38);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('Cells for research', 'cell', 39);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('Cell culture', 'cultcell', 40);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('Cultured virus for research', 'viralstock', 41);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('This sample type is not identifiable by title or box', 'NoID', 42);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('RNA', 'RNA', 43);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('Proteins used for research', 'proteins', 44);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('sputum', '45', 45);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('stool', 'stool', 46);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('Oral Swab', '850', 47);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('diluted DNA', 'dil-DNA', 48);
insert into bhp_lab_aliquottype (name,short_name, display_index) values ('Placenta', 'PLAC', 49);

