from registered_subject_model_admin import RegisteredSubjectModelAdmin
from main import MaternalDeathAdmin
from maternal_consent_admin import MaternalConsentAdmin, MaternalConsentUpdateAdmin
from maternal_visit_admin import MaternalVisitAdmin
from maternal_feeding_choice_admin import FeedingChoiceAdmin, FeedingChoiceSectionOneAdmin, FeedingChoiceSectionTwoAdmin, FeedingChoiceSectionThreeAdmin
from maternal_eligibility_admin import MaternalEligibilityAnteAdmin, MaternalEligibilityPostAdmin
from maternal_enroll_admin import MaternalEnrollAdmin, MaternalEnrollDemAdmin
from maternal_lab_del_admin import MaternalLabDelAdmin
from maternal_locator_admin import MaternalLocatorAdmin
from maternal_arv_admin import *
from maternal_post_fu_admin import *
from my_base_registration_model_admin import MyBaseRegistrationModelAdmin
from maternal_off_study_admin import MaternalOffStudyAdmin
from post_natal_infant_feeding_survey_admin import PostNatalInfantFeedingSurveyAdmin
